### ISSUE TITLE
Python client reference is not being built

### ISSUE THREAD

**Issue by apdavison** [electronicvisions/hbp-sp9-guidebook#15]
presumably because the nmpi module is not available on the build machine (Jenkins?)

(see https://electronicvisions.github.io/hbp-sp9-guidebook/reference/python_client.html)

**Comment by muffgaga** [comment]
Fixed by installing `nmpi` into a `virtualenv` and providing SPHINXBUILD with the virtualenv's `python` interpreter:
```
make clean SPHINXBUILD='python `which sphinx-build`'
make latexpdf SPHINXBUILD='python `which sphinx-build`'
make singlehtml SPHINXBUILD='python `which sphinx-build`'
make dirhtml SPHINXBUILD='python `which sphinx-build`'
make html SPHINXBUILD='python `which sphinx-build`'
```
